import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Exemplos de Data Fetching no Next.js - TecBoard
        </p>

        <div className={styles.grid}>
          <a href="/server-side" className={styles.card}>
            <h2>getServerSideProps &rarr;</h2>
            <p>Exemplo de Server-Side Rendering (SSR) com dados dinâmicos.</p>
          </a>

          <a href="/static" className={styles.card}>
            <h2>getStaticProps &rarr;</h2>
            <p>Exemplo de Static Site Generation (SSG) com dados estáticos.</p>
          </a>

          <a href="/posts" className={styles.card}>
            <h2>getStaticPaths &rarr;</h2>
            <p>Páginas dinâmicas com getStaticProps + getStaticPaths.</p>
          </a>

          <a href="/isr-example" className={styles.card}>
            <h2>ISR - Revalidação &rarr;</h2>
            <p>Incremental Static Regeneration com revalidação automática.</p>
          </a>
        </div>

        <div style={{ marginTop: '3rem', maxWidth: '800px' }}>
          <h2 style={{ textAlign: 'center', marginBottom: '2rem' }}>Quando usar cada método:</h2>
          
          <div style={{ display: 'grid', gap: '1rem', fontSize: '14px' }}>
            <div style={{ padding: '1rem', border: '1px solid #eaeaea', borderRadius: '8px' }}>
              <h3>🔄 getServerSideProps (SSR)</h3>
              <p>Use quando os dados mudam frequentemente ou dependem da requisição (headers, cookies, query params)</p>
            </div>
            
            <div style={{ padding: '1rem', border: '1px solid #eaeaea', borderRadius: '8px' }}>
              <h3>⚡ getStaticProps (SSG)</h3>
              <p>Use para dados que não mudam frequentemente. Máxima performance.</p>
            </div>
            
            <div style={{ padding: '1rem', border: '1px solid #eaeaea', borderRadius: '8px' }}>
              <h3>🎯 getStaticPaths</h3>
              <p>Use com getStaticProps para páginas dinâmicas (ex: /posts/[id])</p>
            </div>
            
            <div style={{ padding: '1rem', border: '1px solid #eaeaea', borderRadius: '8px' }}>
              <h3>🔄⚡ ISR</h3>
              <p>Combine SSG com revalidação automática. Performance + dados atualizados.</p>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
